# Generated by Django 3.2.9 on 2021-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='user/img/icon'),
        ),
    ]
