# Generated by Django 3.2 on 2022-01-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0008_auto_20220120_1442'),
        ('users', '0006_alter_profile_favorite_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_anime',
            field=models.ManyToManyField(to='anime_data.AnimeData', verbose_name='お気に入りのアニメ'),
        ),
    ]
