# Generated by Django 3.2.9 on 2021-11-11 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterdata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persondata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
