# Generated by Django 3.2 on 2022-01-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0002_auto_20211111_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animedata',
            name='casts',
        ),
    ]
