# Generated by Django 3.2 on 2022-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0003_remove_animedata_casts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.TextField(blank=True, null=True, verbose_name='シリーズ名')),
                ('nameEn', models.TextField(blank=True, null=True, verbose_name='シリーズ名EN')),
                ('nameRo', models.TextField(blank=True, null=True, verbose_name='シリーズ名RO')),
            ],
            options={
                'verbose_name_plural': 'AnimeSeriesData',
                'db_table': 'anime_series_db',
            },
        ),
        migrations.CreateModel(
            name='EpisodesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('numberText', models.TextField(blank=True, null=True, verbose_name='話数')),
                ('title', models.TextField(blank=True, null=True, verbose_name='エピソードタイトル')),
            ],
            options={
                'verbose_name_plural': 'EpisodesData',
                'db_table': 'anime_episodes_db',
            },
        ),
        migrations.CreateModel(
            name='StaffsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.TextField(blank=True, null=True, verbose_name='スタッフ名')),
                ('roleOther', models.TextField(blank=True, null=True, verbose_name='職業')),
                ('roleOtherEn', models.TextField(blank=True, null=True, verbose_name='職業EN')),
            ],
            options={
                'verbose_name_plural': 'StaffsData',
                'db_table': 'anime_staffs_db',
            },
        ),
        migrations.AddField(
            model_name='animedata',
            name='character',
            field=models.ManyToManyField(to='anime_data.CharacterData'),
        ),
        migrations.AddField(
            model_name='animedata',
            name='person',
            field=models.ManyToManyField(to='anime_data.PersonData'),
        ),
        migrations.RemoveField(
            model_name='animedata',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='animedata',
            name='seriesList',
        ),
        migrations.RemoveField(
            model_name='animedata',
            name='staffs',
        ),
        migrations.AddField(
            model_name='animedata',
            name='episodes',
            field=models.ManyToManyField(to='anime_data.EpisodesData'),
        ),
        migrations.AddField(
            model_name='animedata',
            name='seriesList',
            field=models.ManyToManyField(to='anime_data.AnimeSeriesData'),
        ),
        migrations.AddField(
            model_name='animedata',
            name='staffs',
            field=models.ManyToManyField(to='anime_data.StaffsData'),
        ),
    ]
