# Generated by Django 3.2 on 2022-01-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0004_auto_20220119_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterdata',
            name='series',
        ),
    ]
