# Generated by Django 3.2 on 2022-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0005_remove_characterdata_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animedata',
            name='character',
        ),
        migrations.RemoveField(
            model_name='animedata',
            name='person',
        ),
        migrations.CreateModel(
            name='CastsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.TextField(verbose_name='声優名')),
                ('nameEn', models.TextField(verbose_name='声優名EN')),
                ('character', models.ManyToManyField(to='anime_data.CharacterData')),
                ('person', models.ManyToManyField(to='anime_data.PersonData')),
            ],
            options={
                'verbose_name_plural': 'CastsData',
                'db_table': 'anime_casts_db',
            },
        ),
        migrations.AddField(
            model_name='animedata',
            name='casts',
            field=models.ManyToManyField(to='anime_data.CastsData'),
        ),
    ]
