# Generated by Django 3.2 on 2022-01-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0006_auto_20220119_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='castsdata',
            name='sortNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='ソート番号'),
        ),
        migrations.AddField(
            model_name='characterdata',
            name='bloodTypeEn',
            field=models.TextField(blank=True, null=True, verbose_name='血液型EN'),
        ),
        migrations.AlterField(
            model_name='castsdata',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='声優名'),
        ),
        migrations.AlterField(
            model_name='castsdata',
            name='nameEn',
            field=models.TextField(blank=True, null=True, verbose_name='声優名EN'),
        ),
        migrations.AlterField(
            model_name='characterdata',
            name='birthdayEn',
            field=models.TextField(blank=True, null=True, verbose_name='誕生日EN'),
        ),
    ]
