# Generated by Django 3.2 on 2022-01-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0007_auto_20220120_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesdata',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='第◯話'),
        ),
        migrations.AlterField(
            model_name='episodesdata',
            name='numberText',
            field=models.TextField(blank=True, null=True, verbose_name='第◯話テキスト'),
        ),
    ]
